#!/bin/bash

# shellcheck disable=SC2034
declare -f assertConfirmation &>/dev/null ||  source "$HOME/.dotfiles/install/declarations"

if assertConfirmation "Update the system?"; then
    echo "Updating the system"
    echo "========================================================================"
    sudo apt-get -y --force-yes update
    sudo apt-get -y --force-yes upgrade
    echo "========================================================================"
    echo "System updated"
    echo "========================================================================"
fi

if grep -q "^flags.*\ hypervisor\ " /proc/cpuinfo  &&  assertConfirmation "Install Virtual Machine extras?"; then
    source "$INSTALL/virtual-machine"
fi

if ! (( ${autoConfirm:?} )); then
    source "$INSTALL/remove-packages"
fi

source "$INSTALL/install-packages"

if [[ ! "$(tmux -V)" == *"2.3"* ]]  &&  assertConfirmation "Install tmux?"; then
    source "$DOTFILES/install/tmux-install"
fi

if [ ! -d ~/Downloads/jd2 ]  &&  assertConfirmation "Install jDownloader?"; then
    source "$DOTFILES/install/jdownloader-install" # TODO: Downloads may not exist.
fi

source "$INSTALL/flux-install"

if [ "${MACHINE_TYPE}" == 64 ]  &&  assertConfirmation "Install Google Chrome?"; then
        sudo apt-get install libxss1 libappindicator1 libindicator7
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo dpkg -i google-chrome*.deb
        sudo apt-get install -f
        rm google-chrome-stable_current_amd64.deb
        echo "========================================================================"
        echo "Gogle Chrome Installed"
        echo "========================================================================"
fi

if ! (( autoConfirm ))  &&  [ "${MACHINE_TYPE}" == 64 ]; then
    clear
    read -n 1 -p "Install Selenium? (yes/No) "
    printf '\n========================================================================'
    if [[ $REPLY =~ ^([Yy]|[Ss])$ ]]; then
        # Instalar xvfb
        sudo apt-get install xvfb
        # Instalar ChromeDriver
        wget -N http://chromedriver.storage.googleapis.com/2.20/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        chmod +x chromedriver

        sudo mv -f chromedriver /usr/local/share/chromedriver
        rm chromedriver_linux64.zip
        sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
        sudo ln -s /usr/local/share/chromedriver /usr/bin/chromedriver
        echo "========================================================================"
    fi
fi
