#!/bin/bash

sudo apt-get -y install task mpd
sudo pip install speedtest-cli
sudo ln -s /usr/bin/"$(apt-search-cache)"
sudo apt-get-latest -y install "lua*"
sudo ln -s /usr/bin/"$(apt-cache-search-latest \"lua*\")" /usr/bin/lua

killall conky 2>/dev/null

# if there is no hidden folder autostart then make one
[ -d ~/.config/autostart ] || mkdir -p ~/.config/autostart

# if there is no hidden folder conky then make one
[ -d ~/.config/conky ] || mkdir -p ~/.config/conky

# if there is no hidden folder fonts then make one
[ -d ~/.fonts ] || mkdir -p ~/.fonts

read -n 1 -p "Everything in folder ~/.config/conky will be deleted. Are you sure? [y/N]? "
if [[ $REPLY =~ ^([Yy]|[Ss])$ ]]; then
    rm -rf ~/.config/conky/
else
    echo "No files have been changed in folder ~/.config/conky."
    echo "Script ended!"
    exit
fi
#cp -r * ~/.config/conky/
#mkdir -p "$HOME/.config/conky/themes/haxOS_Conky"
#cp -r "$HOME/.dotfiles/conky/." "$HOME/.config/conky/themes/haxOS_Conky"
cp -r ~/.dotfiles/conky/. ~/.config/conky/
echo "The files have been copied to ~/.config/conky."
# the standard place conky looks for a config file

echo "Making sure conky autostarts next boot."
cat << EOF > $HOME/.config/autostart/start-conky.desktop
[Desktop Entry]
Type=Application
Exec=$HOME/.dotfiles/conky/start-conky.desktop
Icon=conky
X-GNOME-Autostart-enabled=true
X-MATE-Autostart-enabled=true
NoDisplay=false
Hidden=false
Name[en_US]=start-conky
Comment[en_US]=
X-GNOME-Autostart-Delay=30
EOF

conky -q -c ~/.config/conky/start-conky.desktop
