#!/bin/bash

#### System Settings
    # Disable the Switch User option
    dconf write /org/cinnamon/desktop/lockdown/disable-user-switching true
  #### Appearance
    #### Backgrounds
    # Select image
    # dconf write /org/cinnamon/desktop/background/picture-uri "'file:///usr/share/backgrounds/linuxmint/default_background.jpg'"
    # Play backgrounds as a slideshow
    dconf write /org/cinnamon/desktop/background/slideshow/slideshow-enabled false
    # Delay (minutes)
    # dconf write /org/cinnamon/desktop/background/slideshow/delay 15
    # Play images in random order
    # dconf write /org/cinnamon/desktop/background/slideshow/random-order true
    # Picture aspect (none, mosaic, centered, scaled, stretched, zoom, spanned)
    # dconf write /org/cinnamon/desktop/background/picture-options "'zoom'"
    # Background gradient (none, horizontal, vertical)
    # dconf write /org/cinnamon/desktop/background/color-shading-type "'horizontal'"
    # Gradient start color
    # dconf write /org/cinnamon/desktop/background/primary-color "'#000000000000'"
    # dconf write /org/cinnamon/desktop/background/color-shading-type "'solid'"

    #### Effects
    # Window effects
    dconf write /org/cinnamon/desktop-effects false
    # Effects on dialog boxes
    dconf write /org/cinnamon/desktop-effects-on-dialogs false
    # Effects on Gtk menus
    dconf write /org/cinnamon/desktop-effects-on-menus false
    # Effects style
    # Fade effect on Cinnamon scrollboxes (like the Menu applications list)
    dconf write /org/cinnamon/enable-vfade false
    # Session startup animation
    dconf write /org/cinnamon/startup-animation false
    # Overlay scroll bars (logout required)
    dconf write /org/cinnamon/desktop/interface/gtk-overlay-scrollbars true

    #### Fonts
    # Default font
    dconf write /org/cinnamon/desktop/interface/font-name "'Noto Sans 14'"
    # Desktop font
    dconf write /org/nemo/desktop/font "'Noto Sans 14'"
    # Document font
    dconf write /org/gnome/desktop/interface/document-font-name "'Noto Sans 14'"
    # Monospace font
    dconf write /org/gnome/desktop/interface/monospace-font-name "'Monospace 14'"
    # Window title font
    dconf write /org/cinnamon/desktop/wm/preferences/titlebar-font "'Noto Sans Bold 11'"

    #### Themes
    # Window borders
    # dconf write /org/cinnamon/desktop/wm/preferences/theme "'Mint-Y-Dark'"
    # Icons
    # dconf write /org/cinnamon/desktop/interface/icon-theme "'Mint-Y'"
    # Controls
    # dconf write /org/cinnamon/desktop/interface/gtk-theme "'Mint-Y-Dark'"
    # Mouse Pointer
    # dconf write /org/cinnamon/desktop/interface/cursor-theme "'Adwaita'"
    # Desktop
    # dconf write /org/cinnamon/theme/name "'Mint-Y-Dark'"
      #### Settings
      # Show icons in menus
      dconf write /org/cinnamon/settings-daemon/plugins/xsettings/menus-have-icons true
      # Show icons on buttons
      dconf write /org/cinnamon/settings-daemon/plugins/xsettings/buttons-have-icons false
      # Use a dark theme when available in application

  #### Preferences
    #### Accessibility

    #### Account details

    #### Applets

    #### Date & Time
    # Use 24h clock
    dconf write /org/cinnamon/desktop/interface/clock-use-24h true
    # Display the date
    dconf write /org/cinnamon/desktop/interface/clock-show-date true
    # Display seconds
    dconf write /org/cinnamon/desktop/interface/clock-show-seconds false
    # First day of week (0 local, 1 monday, 7 sunday)
    dconf write /org/cinnamon/desktop/interface/first-day-of-week 1

    #### Desklets
      #### Installed desklets
      dconf write /org/cinnamon/enabled-desklets "['clock@cinnamon.org:0:150:0']"

      #### Available desklets (online)

      #### General Settings
      # Decoration of desklets (0 no decoration, 1 border only, 2 border and header)
      dconf write /org/cinnamon/desklet-decorations 0

    #### Desktop

    #### Extensions

    #### General

    #### Hot Corners

    #### Input Method

    #### Languages

    #### Notifications

    #### Panel
    # Auto-hide panel (true, false, intel)
    dconf write /org/cinnamon/panels-autohide "['1:intel']"
    # Show delay (miliseconds)
    # dconf write /org/cinnamon/panels-show-delay "['1:50']"
    # Hide delay (miliseconds)
    # dconf write /org/cinnamon/panels-hide-delay "['1:100']"
    # Use customized panel size (otherwise it's defined by the theme)
    dconf write /org/cinnamon/panels-resizable "['1:true']" # This must be true for the following height to take effect.
    # Allow cinnamon to scale panel text and icons according to panel heights
    dconf write /org/cinnamon/panels-scale-text-icons "['1:true']"
    # Panel height
    dconf write /org/cinnamon/panels-height "['1:35']"
    # Allow the pointer to pass through the edges of panels
    # dconf write /org/cinnamon/no-adjacent-panel-barriers false

    #### Preferred Applications
      #### Removable media
      # Prompt or start programs on media insertion
      dconf write /org/cinnamon/desktop/media-handling/autorun-never false
      # Select an application for software CDs

    #### Privacy
    # Remember recently accessed files
    dconf write /org/cinnamon/desktop/privacy/remember-recent-files true
    # Never forget old files
    dconf write /org/cinnamon/desktop/privacy/recent-files-max-age -1
    # Number of days to remember old files
    dconf write /org/cinnamon/desktop/privacy/recent-files-max-age 30

    #### Screensaver
    # Select screensaver
    # dconf write /org/cinnamon/desktop/screensaver/screensaver-name "''"
    # dconf write /org/cinnamon/desktop/screensaver/screensaver-name "'xscreensaver@cinnamon.org'"
    # dconf write /org/cinnamon/desktop/screensaver/xscreensaver-hack "'glmatrix'"
    # dconf write /org/cinnamon/desktop/screensaver/screensaver-name "'xscreensaver@cinnamon.org'"
    # dconf write /org/cinnamon/desktop/screensaver/xscreensaver-hack "'xmatrix'"
      #### Settings
      # Lock the computer when put to sleep
      dconf write /org/cinnamon/settings-daemon/plugins/power/lock-on-suspend false
      # Lock the computer when the screen turns off
      dconf write /org/cinnamon/desktop/screensaver/lock-enabled false
      # Delay before locking the screen
      # dconf write /org/cinnamon/desktop/screensaver/lock-delay "uint32 300"
      # Lock the computer when inactive (0 never)
      dconf write /org/cinnamon/desktop/session/idle-delay "uint32 0"
      # dconf write /org/cinnamon/desktop/session/idle-delay "uint32 600"
      # Show message when the screen is locked
      # dconf write /org/cinnamon/desktop/screensaver/default-message "'locked'"
      # Font
      # dconf write /org/cinnamon/desktop/screensaver/font-message "'Noto Sans 14'"
      # Ask for a custom message when locking the screen from the menu
      dconf write /org/cinnamon/desktop/screensaver/ask-for-away-message false

      #### Date
      # Use a custom date and time format
      # Time Font
      # Date Font

    #### Startup Applications

    #### Windows
      #### Titlebar

      #### Behaviour
      # Window focus mode (click, mouse, sloppy)
      dconf write /org/cinnamon/desktop/wm/preferences/focus-mode "'sloppy'"
      # Automatically raise focussed windows
      dconf write /org/cinnamon/desktop/wm/preferences/auto-raise true
      # Bring windows which require attention to the current workspace
      dconf write /org/cinnamon/bring-windows-to-current-workspace false
      # Prevent focus stealing
      dconf write /org/cinnamon/prevent-focus-stealing false
      # Attach dialog windows to the parent window

      #### Alt-Tab

    #### Window Tiling

    #### Workspaces

  #### Hardware

    #### Bluetooth

    #### Color

    #### Display

    #### Graphics Tablet

    #### Keyboard
      #### Typing
      # Enable key repeat
      dconf write /org/cinnamon/settings-daemon/peripherals/keyboard/repeat true
      # Repeat delay
      dconf write /org/cinnamon/settings-daemon/peripherals/keyboard/delay "uint32 200"
      # Repeat speed
      dconf write /org/cinnamon/settings-daemon/peripherals/keyboard/repeat-interval "uint32 20"
      # Text cursor blinks
      # dconf write /org/cinnamon/desktop/interface/cursor-blink true
      # Blink speed
      # dconf write /org/cinnamon/desktop/interface/cursor-blink-time 1200

      #### Shortcuts
      # ctrl + alt + del to open system manager
      # http://askubuntu.com/questions/597395/how-to-set-custom-keyboard-shortcuts-from-terminal
      # http://www.howtogeek.com/howto/20355/use-ctrlaltdel-for-task-manager-in-linux-to-kill-tasks-easily/
      dconf write /org/cinnamon/desktop/keybindings/custom-list "['custom0', 'custom1', 'custom2']"
      dconf write /org/cinnamon/desktop/keybindings/custom-keybindings/custom0/name "'Task Manager'"
      dconf write /org/cinnamon/desktop/keybindings/custom-keybindings/custom0/command "'gnome-system-monitor'"
      dconf write /org/cinnamon/desktop/keybindings/custom-keybindings/custom0/binding "['<Primary><Alt>KP_Delete']"

      # Kill Window shortcut
      dconf write /org/cinnamon/desktop/keybindings/custom-keybindings/custom1/name "'Kill Window'"
      dconf write /org/cinnamon/desktop/keybindings/custom-keybindings/custom1/command "'xkill'"
      dconf write /org/cinnamon/desktop/keybindings/custom-keybindings/custom1/binding "['<Primary>KP_Delete']"

      # Fix Screenshot Area
      if [ "$DESKTOP" = "cinnamon" ]  &&  [ "$VER" -lt 18 ]  &&  [ ! -f ~/bin/gnome_screenshot_fix_grab_area ]; then
          cat << EOF > ~/bin/gnome_screenshot_fix_grab_area
          !/bin/sh

          sleep 0.125
          gnome-screenshot --area
EOF
      chmod +x ~/bin/gnome_screenshot_fix_grab_area
      fi
      #dconf write /org/cinnamon/desktop/keybindings/custom-keybindings/custom2/name "'Screenshot of Area'"
      #dconf write /org/cinnamon/desktop/keybindings/custom-keybindings/custom2/command "'gnome_screenshot_fix_grab_area.sh'"
      #dconf write /org/cinnamon/desktop/keybindings/custom-keybindings/custom2/binding "['<Shift>Print']"

      #### Layouts options
      # Swap Esc/Lock Mayus
      # http://superuser.com/questions/396988/how-to-remap-capslock-to-esc-in-linux-mint-12
      # http://askubuntu.com/questions/363346/how-to-permanently-switch-caps-lock-and-esc
      # dconf write /org/cinnamon/settings-daemon/peripherals/keyboard/numlock-state "'off'"
      dconf write /org/gnome/libgnomekbd/keyboard/options "['caps\tcaps:swapescape']"

    #### Mouse and Touchpad
      #### Mouse
      # Left handed (mouse buttons inverted)
      # dconf write /org/cinnamon/settings-daemon/peripherals/mouse/left-handed false
      # Show position of pointer when the Control key is pressed
      # dconf write /org/cinnamon/settings-daemon/peripherals/mouse/locate-pointer false
      # Emulate middle click by clicking both left and right buttons
      # dconf write /org/cinnamon/settings-daemon/peripherals/mouse/middle-button-enabled false
      # Pointer size
      # dconf write /org/cinnamon/desktop/interface/cursor-size 30
      # Pointer acceleration
      dconf write /org/cinnamon/settings-daemon/peripherals/mouse/motion-acceleration 4.0
      # Pointer sensitivity
      dconf write /org/cinnamon/settings-daemon/peripherals/mouse/motion-threshold 2.0
      # Double-Click timeout
      # dconf write /org/cinnamon/settings-daemon/peripherals/mouse/double-click 340

      #### Touchpad
      # Enable touchpad
      dconf write /org/cinnamon/settings-daemon/peripherals/touchpad/touchpad-enabled true
      # Tap to click
      dconf write /org/cinnamon/settings-daemon/peripherals/touchpad/tap-to-click true
      # Disable touchpad while typing
      dconf write /org/cinnamon/settings-daemon/peripherals/touchpad/disable-while-typing true
      # Two-finger click emulation (0 disabled, 1 left, 2 middle, 3 right)
      dconf write /org/cinnamon/settings-daemon/peripherals/touchpad/two-finger-click 3
      # Three-finger click emulation
      dconf write /org/cinnamon/settings-daemon/peripherals/touchpad/three-finger-click 2
      # Reverse scrolling direction
      dconf write /org/cinnamon/settings-daemon/peripherals/touchpad/natural-scroll false
      # Vertical edge scrolling
      dconf write /org/cinnamon/settings-daemon/peripherals/touchpad/vertical-edge-scrolling true
      # Horizontal edge scrolling
      dconf write /org/cinnamon/settings-daemon/peripherals/touchpad/horizontal-edge-scrolling true
      # Vertical two-finger scrolling
      dconf write /org/cinnamon/settings-daemon/peripherals/touchpad/vertical-two-finger-scrolling true
      # Horizontal two-finger scrolling
      dconf write /org/cinnamon/settings-daemon/peripherals/touchpad/horizontal-two-finger-scrolling true
      # Pointer acceleration
      dconf write /org/cinnamon/settings-daemon/peripherals/touchpad/motion-acceleration 5.4820717131474108 # A fraction is needed.
      # Pointer sensitivity
      dconf write /org/cinnamon/settings-daemon/peripherals/touchpad/motion-threshold 2

    #### Networking

    #### Power Management
    # Turn off the screen when inactive
    dconf write /org/cinnamon/settings-daemon/plugins/power/sleep-display-ac 0 # never
    dconf write /org/cinnamon/settings-daemon/plugins/power/sleep-display-battery 0

    # Suspend when inactive
    dconf write /org/cinnamon/settings-daemon/plugins/power/sleep-inactive-ac-timeout 0
    dconf write /org/cinnamon/settings-daemon/plugins/power/sleep-inactive-battery-timeout 0

    # When lid is closed
    dconf write /org/cinnamon/settings-daemon/plugins/power/lid-close-ac-action "'nothing'"
    dconf write /org/cinnamon/settings-daemon/plugins/power/lid-close-battery-action "'nothing'"

    # When the power button is pressed (blank, suspend, shutdown, hibernate, interactive, nothing)
    dconf write /org/cinnamon/settings-daemon/plugins/power/button-power "'suspend'"

    # When the battery is critically low
    dconf write /org/cinnamon/settings-daemon/plugins/power/critical-battery-action "'hibernate'"

    # Perform lid-closed action even with external monitors attached
    dconf write /org/cinnamon/settings-daemon/plugins/power/lid-close-suspend-with-external-monitor false

    # On battery, dim screen when inactive
    dconf write /org/cinnamon/settings-daemon/plugins/power/idle-dim-battery false

    # Brightness level when inactive
    # dconf write /org/cinnamon/settings-daemon/plugins/power/idle-brightness 30 # dim to 30%

    # Dim screen after inactive for
    # dconf write /org/cinnamon/settings-daemon/plugins/power/idle-dim-time 1200 # dim after x seconds

    #### Printers

    #### Sound
    # Starting Cinnamon
    dconf write /org/cinnamon/sounds/login-enabled false
    # Leaving Cinnamon
    dconf write /org/cinnamon/sounds/logout-enabled false
    # Switching workspace
    dconf write /org/cinnamon/sounds/switch-enabled false
    # Opening new windows
    dconf write /org/cinnamon/sounds/map-enabled false
    # Closing windows
    dconf write /org/cinnamon/sounds/close-enabled false
    # Minimizing windows
    dconf write /org/cinnamon/sounds/minimize-enabled false
    # Maximizing windows
    dconf write /org/cinnamon/sounds/maximize-enabled false
    # Unmaximizing windows
    dconf write /org/cinnamon/sounds/unmaximize-enabled false
    # Tiling and snapping windows
    dconf write /org/cinnamon/sounds/tile-enabled false
    # Inserting a device
    dconf write /org/cinnamon/sounds/plug-enabled false
    # Removing a device
    dconf write /org/cinnamon/sounds/unplug-enabled false
    # Changing the sound volume
    dconf write /org/cinnamon/desktop/sound/volume-sound-enabled false

  #### Administration

#### Programs Settings
  #### Terminal
    profile="$(dconf dump / |grep legacy/profiles:/ |sed -r 's/^\[|\]$//g' |head -n1)"
    # Change terminal prompt to >
    # cat /etc/bash.bashrc | grep "PS1='" # comment this line
    # echo PS1=' > ' >> ~/.profile # add this instead

    #### General
    # Profile name
    # dconf write /$profile/visible-name "'Original'"
    # Initial terminal size
    # dconf write /$profile/default-size-columns 240
    # dconf write /$profile/default-size-rows 100
    # Cursor shape (block, ibeam, underline)
    # dconf write /$profile/cursor-shape "'block'"
    # Terminal bell
    # dconf write /$profile/audible-bell false

    # Allow bold text
    # dconf write /$profile/allow-bold true
    # Rewrap on resize
    # dconf write /$profile/rewrap-on-resize true
    # Custom Font
    # dconf write /$profile/use-system-font false
    # dconf write /$profile/font "'Hack 14'"
    # dconf write /$profile/visible-name "'Original'"

    #### Command

    #### Colors
    # Use colors from system theme
    # dconf write /$profile/use-theme-colors true
    # Built-in schemes
    # select solarized dark
    # dconf write /$profile/foreground-color "'rgb(131,148,150)'"
    # dconf write /$profile/background-color "'rgb(0,43,54)'"
    # dconf write /$profile/palette "['rgb(7,54,66)', 'rgb(220,50,47)', 'rgb(133,153,0)', 'rgb(181,137,0)', 'rgb(38,139,210)', 'rgb(211,54,130)', 'rgb(42,161,152)', 'rgb(238,232,213)', 'rgb(0,43,54)', 'rgb(203,75,22)', 'rgb(88,110,117)', 'rgb(101,123,131)', 'rgb(131,148,150)', 'rgb(108,113,196)', 'rgb(147,161,161)', 'rgb(253,246,227)']"
    # select green on black
    # dconf write /$profile/foreground-color "'rgb(0,255,0)'"
    # dconf write /$profile/background-color "'rgb(0,0,0)'"
    # Use transparent background
    dconf write /$profile/use-transparent-background false

    #### Scrolling
    # Show scrollbar (never, always)
    # dconf write /$profile/scrollbar-policy "'never'"
    # Scroll on output
    # dconf write /$profile/scroll-on-output false
    # Scroll on keystroke
    # dconf write /$profile/scroll-on-keystroke true
    # Limit scrollback
    # dconf write /$profile/scrollback-unlimited true
    # dconf write /$profile/scrollback-lines 10000

    #### Compatiblity

  #### Nemo File Manager settings
  # dconf write /org/nemo/window-state/sidebar-bookmark-breakpoint 5
  # dconf write /org/nemo/window-state/start-with-sidebar true # can be toggled with F9
  dconf write /org/nemo/window-state/sidebar-width 200
  dconf write /org/nemo/window-state/maximized true
  # dconf write /org/nemo/preferences/show-hidden-files true # can be toggled with ctrl + h
    #### Views
    # View new folders using (icon-view, list-view, compact-view)
    # dconf write /org/nemo/preferences/default-folder-viewer "'icon-view'"
    # Arrange items
    # dconf write /org/nemo/preferences/default-sort-order "'name'"
    # Sort folders before files
    # dconf write /org/nemo/preferences/sort-directories-first true
    # Icon view default zoom level (smallest, smaller, small, standard, large, larger, largest)
    dconf write /org/nemo/icon-view/default-zoom-level "'large'"
    # Text beside icons
    # dconf write /org/nemo/icon-view/labels-beside-icons false
    # Use compact layout
    # dconf write /org/nemo/icon-view/default-use-tighter-layout false
    # Compact view default zoom level (smallest, smaller, small, standard, large, larger, largest)
    # dconf write /org/nemo/compact-view/default-zoom-level "'small'"
    # All columns have the same width
    # dconf write /org/nemo/compact-view/all-columns-have-same-width false
    # List view default zoom level
    # dconf write /org/nemo/list-view/default-zoom-level "'smaller'"
    # Tree view show only folders
    # dconf write /org/nemo/sidebar-panels/tree/show-only-directories true

    #### Behavior
    # Single click to open items
    dconf write /org/nemo/preferences/click-policy "'single'"
    # Click twice with a pause in between to rename items
    # dconf write /org/nemo/preferences/quick-renames-with-pause-in-between true
    # Open each folder in its own window
    # dconf write /org/nemo/preferences/always-use-browser false
    # Always start in dual-panel view
    # dconf write /org/nemo/preferences/start-with-dual-pane false
    # Ignore per-folder view preferences
    # dconf write /org/nemo/preferences/ignore-view-metadata false
    # Disable file operation queueing
    # dconf write /org/nemo/preferences/never-queue-file-ops false

    # Executable text files (launch, display, ask)
    dconf write /org/nemo/preferences/executable-text-activation "'display'"

    # Ask before emptying the Trash or deleting files
    # dconf write /org/nemo/preferences/confirm-trash false
    # Include a Delete command that bypasses Trash
    dconf write /org/nemo/preferences/enable-delete true
    # Bypass the Trash when the Delete key is pressed
    dconf write /org/nemo/preferences/swap-trash-delete true

    # Automatically mount removable media when inserted and on startup
    dconf write /org/cinnamon/desktop/media-handling/automount true
    # Automatically open a folder for automounted media
    dconf write /org/cinnamon/desktop/media-handling/automount-open false
    # Prompt for autorun/autostart programs when media are inserted
    dconf write /org/cinnamon/desktop/media-handling/autorun-never false
    # Automatically close the device's tab, pane, or window when a device is unmounted or ejected
    dconf write /org/nemo/preferences/close-device-view-on-device-eject true

    #### Display
    # Chose the order of information to appear beneath icon names. More information will appear
    # when zooming in closer. (none, size, type, detailed_type, date_modified, date_accessed, owner,
    # group, permissions, octal_permissions, mime_type, where)
    # dconf write /org/nemo/icon-view/captions "['none', 'size', 'date_modified']"
    # Date format (locale, iso, informal)
    # dconf write /org/nemo/preferences/date-format "'locale'"
    # Show the full path in the title bar and tab bars
    dconf write /org/nemo/preferences/show-full-path-titles true
    # File size prefixes (base-10, base-10-full, base-2, base-2-full)
    # dconf write /org/nemo/preferences/size-prefixes "'base-10'"
    # Show advanced permissions in the file property dialog
    dconf write /org/nemo/preferences/show-advanced-permissions true
    # List bookmarks in the menu
    # dconf write /org/nemo/preferences/show-bookmarks-in-to-menus true
    # List devices and network locations in the menu
    # dconf write /org/nemo/preferences/show-places-in-to-menus true

    #### List Columns
    dconf write /org/nemo/list-view/default-visible-columns "['name', 'size', 'type', 'date_modified', 'owner', 'permissions']"

    #### Preview
    # Show text in icons (always, local-only, never)
    # dconf write /org/nemo/preferences/show-icon-text "'never'"

    # Show thumbnails
    dconf write /org/nemo/preferences/show-image-thumbnails "'never'"
    # Only for files smaller than:
    # dconf write /org/nemo/preferences/thumbnail-limit "uint64 4294967295"

    # Show tooltips in icon and compact view
    # dconf write /org/nemo/preferences/tooltips-in-icon-view false
    # Show tooltips in list views
    # dconf write /org/nemo/preferences/tooltips-in-list-view false
    # Show tooltips on the desktop
    # dconf write /org/nemo/preferences/tooltips-on-desktop false

    #### Toolbar
    # Show previous button
    # dconf write /org/nemo/preferences/show-previous-icon-toolbar true
    # Show next button
    # dconf write /org/nemo/preferences/show-next-icon-toolbar true
    # Show up button
    # dconf write /org/nemo/preferences/show-up-icon-toolbar true
    # Show refresh button
    # dconf write /org/nemo/preferences/show-reload-icon-toolbar false
    # Show computer button
    # dconf write /org/nemo/preferences/show-computer-icon-toolbar false
    # Show home button
    # dconf write /org/nemo/preferences/show-home-icon-toolbar true # small icon on the left of the path
    # Show location entry/breadcrumbs toggle button
    # dconf write /org/nemo/preferences/show-edit-icon-toolbar true
    # Show open in terminal button
    # dconf write /org/nemo/preferences/show-open-in-terminal-toolbar true
    # Show new folder button
    dconf write /org/nemo/preferences/show-new-folder-icon-toolbar true # small icon next to the search icon
    # Show search button
    dconf write /org/nemo/preferences/show-search-icon-toolbar true
    # Show icon view button
    dconf write /org/nemo/preferences/show-icon-view-icon-toolbar false
    # Show list view button
    dconf write /org/nemo/preferences/show-list-view-icon-toolbar false
    # Show compact view button
    dconf write /org/nemo/preferences/show-compact-view-icon-toolbar false

  #### Xplayer
    # Repeat mode
    # dconf write /org/x/player/repeat false
    # Shuffle mode
    # dconf write /org/x/player/shuffle false

    #### General
    # Start playing files from last position
    dconf write /org/x/player/remember-position true

    # Load subtitle files when movie is loaded
    dconf write /org/x/player/autoload-subtitles true
    # Font:
    # dconf write /org/x/player/subtitle-font "'Sans Bold 20'"

    # Load chapter files when movie is loaded
    # dconf write /org/x/player/autoload-chapters true

    #### Display
    # Resize the window when a new video is loaded
    # dconf write /org/x/player/auto-resize true

    #### Audio

  #### Weather Desklet
  # http://stackoverflow.com/questions/12452961/how-to-get-city-code-weather-in-accuweather
  # http://pastebin.com/dbtemx5F
  # City Name = "Madrid, ES" Location = "EUR|ES|SP013|MADRID" Country = "Spain"
  # City Name = "Malaga, ES" Location = "EUR|ES|SP001|MÁLAGA" Country = "Spain"
  # dconf write /org/cinnamon/next-desklet-id 1
  # dconf write /org/cinnamon/enabled-desklets "['accudesk@logan:0:1025:25']"

  #### Wifi Applet
  dconf write /org/gnome/nm-applet/disable-disconnected-notifications true
  dconf write /org/gnome/nm-applet/disable-connected-notifications true

  #### Update Manager
  dconf write /com/linuxmint/updates/hide-window-after-update true
  dconf write /com/linuxmint/updates/hide-systray true
  dconf write /com/linuxmint/updates/default-repo-is-ok true
  dconf write /com/linuxmint/updates/level1-is-visible true
  dconf write /com/linuxmint/updates/level2-is-visible true
  dconf write /com/linuxmint/updates/level3-is-visible true
  dconf write /com/linuxmint/updates/level4-is-visible true
  dconf write /com/linuxmint/updates/level5-is-visible true
  dconf write /com/linuxmint/updates/level1-is-safe true
  dconf write /com/linuxmint/updates/level2-is-safe true
  dconf write /com/linuxmint/updates/level3-is-safe true
  dconf write /com/linuxmint/updates/level4-is-safe false
  dconf write /com/linuxmint/updates/level5-is-safe false
  dconf write /com/linuxmint/updates/security-updates-are-visible true
  dconf write /com/linuxmint/updates/security-updates-are-safe false
  dconf write /com/linuxmint/updates/kernel-updates-are-visible true
  dconf write /com/linuxmint/updates/kernel-updates-are-safe false
  dconf write /com/linuxmint/updates/refresh-days 7
  dconf write /com/linuxmint/updates/autorefresh-days 7
  dconf write /com/linuxmint/updates/dist-upgrade true
  dconf write /com/linuxmint/updates/blacklisted-packages "@as []"
################################################################################
