#!/bin/bash

# shellcheck disable=SC2034
declare -f assertConfirmation &>/dev/null ||  source "$HOME/.dotfiles/install/declarations"

mkdir -p ~/tmp  &&  cd ~/tmp
git clone https://github.com/powerline/fonts
cd fonts || { echo "Fonts directory doesn't exist" ; exit ; }
./install.sh
cd  &&  rm -rf ~/tmp

if [ -f ~/.local/share/fonts/Hack-Regular.ttf ]; then
  rm -rf ~/.local/share/fonts
  wget https://github.com/Lokaltog/powerline/raw/develop/font/PowerlineSymbols.otf https://github.com/Lokaltog/powerline/raw/develop/font/10-powerline-symbols.conf
  mkdir -p ~/.fonts/ && mv PowerlineSymbols.otf ~/.fonts/
  fc-cache -vf ~/.fonts
  mkdir -p ~/.config/fontconfig/conf.d/ && mv 10-powerline-symbols.conf ~/.config/fontconfig/conf.d/
fi
