#!/bin/bash

dconf write /org/gnome/nm-applet/disable-disconnected-notifications true
dconf write /org/gnome/nm-applet/disable-connected-notifications true
#dconf write /org/gnome/libgnomekbd/keyboard/options "['caps\tcaps:swapescape']"
dconf write /org/gnome/desktop/input-sources/xkb-options "['caps:swapescape']"

################################################################################
#### File Manager
################################################################################
dconf write /org/gnome/nautilus/preferences/always-use-location-entry true
dconf write /org/gnome/nautilus/list-view/default-visible-columns "['name', \
  'size', 'type', 'date_modified', 'owner', 'permissions']"
dconf write /org/gnome/nautilus/icon-view/default-zoom-level "'large'"
dconf write /org/gnome/nautilus/preferences/click-policy "'single'"
dconf write /org/gnome/nautilus/preferences/enable-delete true
dconf write /org/gnome/nautilus/preferences/confirm-trash false
dconf write /org/gnome/nautilus/preferences/show-image-thumbnails "'local-only'"
dconf write /org/gnome/nautilus/window-state/maximized true
dconf write /org/gnome/nautilus/window-state/start-with-sidebar false

################################################################################
#### Multimedia Player
################################################################################

################################################################################
#### Desktop
################################################################################
dconf write /org/gnome/desktop/lockdown/disable-lock-screen true
dconf write /org/gnome/desktop/lockdown/disable-user-switching true
dconf write /org/gnome/desktop/peripherals/keyboard/repeat true
dconf write /org/gnome/desktop/peripherals/keyboard/delay "uint32 200"
dconf write /org/gnome/desktop/peripherals/keyboard/repeat-interval "uint32 20"
dconf write /org/gnome/desktop/peripherals/mouse/natural-scroll false
dconf write /org/gnome/desktop/peripherals/touchpad/edge-scrolling-enabled true

dconf write /org/gnome/desktop/interface/can-change-accels false
dconf write /org/gnome/desktop/interface/cursor-blink true
dconf write /org/gnome/desktop/interface/cursor-blink-time 1200
dconf write /org/gnome/desktop/interface/cursor-size 24
dconf write /org/gnome/desktop/interface/cursor-theme "'Adwaita'"
dconf write /org/gnome/desktop/interface/gtk-theme "'Mint-Y-Dark'"
dconf write /org/gnome/desktop/interface/icon-theme "'Mint-Y'"
dconf write /org/gnome/desktop/interface/menus-have-icons true
dconf write /org/gnome/desktop/interface/toolbar-style "'icons'"
dconf write /org/gnome/desktop/interface/show-battery-percentage true

#dconf write /org/gnome/desktop/peripherals/mouse/motion-threshold 2.0
#dconf write /org/gnome/desktop/peripherals/mouse/motion-acceleration 5.5
dconf write /org/gnome/settings-daemon/plugins/color/night-light-enabled true
dconf write /org/gnome/settings-daemon/plugins/color/night-light-schedule-automatic true
dconf write /org/gnome/settings-daemon/plugins/media-keys/terminal "''"
dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings \
  "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/name "'Terminal Fullscreen'"
dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/command "'gnome-terminal --window --full-screen'"
dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/binding "'<Primary><Alt>t'"
dconf write /org/gnome/desktop/wm/preferences/button-layout "'appmenu:minimize,maximize,close'"

dconf write /org/gnome/desktop/wm/preferences/action-middle-click-titlebar "'lower'"
dconf write /org/gnome/desktop/wm/preferences/audible-bell false
dconf write /org/gnome/desktop/wm/preferences/num-workspaces 8

profile="$(dconf dump / | grep /legacy/profiles:/ | sed -r 's/^\[|\]$//g' | head -n1)"
dconf write /$profile/audible-bell false
dconf write /$profile/use-transparent-background false
dconf write /$profile/scrollbar-policy "'never'"
dconf write /$profile/scroll-on-output false
dconf write /$profile/scroll-on-keystroke true
dconf write /$profile/scrollback-unlimited true
dconf write /$profile/scrollback-lines 10000
dconf write /org/gnome/terminal/legacy/default-show-menubar false
# Built-in schemes
# onedark TODO: fix this
#dconf write /org/mate/terminal/global/profile-list "['defaul', 'profile0']"
#dconf write /org/gnome/terminal/legacy/profiles:/list "['b1dcc9dd-5262-4d8d-a863-c897e6d979b9', 'f0a8696e-5d7d-4300-b432-6ea0060c1fd6']"
#dconf write /$profile/visible-name "'onedark'"
#dconf write /org/mate/terminal/profiles/profile0/palette "'#28272C2B3433:\
  #E0DF6C6B7574:#9897C3C27978:#E5E5C0BF7B7B:#6160AFAFEFEF:#C6C57877DDDD:\
  #5656B6B6C2C1:#63636D6C8382:#28272C2B3433:#BEBE504F4646:#9897C3C27978:\
  #D1D09A996665:#6160AFAFEFEF:#C6C57877DDDD:#5656B6B6C2C1:#5C5B6363706F'"
#dconf write /org/mate/terminal/profiles/profile0/background-color "'#28272C2B3433'"
#dconf write /org/mate/terminal/profiles/profile0/foreground-color "'#ABAAB2B1BFBF'"
#onedark="$(dconf dump / | grep /legacy/profiles:/ | sed -r 's/^\[|\]$//g' | head -n1)"
#/org/gnome/terminal/legacy/profiles:/default "'f0a8696e-5d7d-4300-b432-6ea0060c1fd6'"
#/org/gnome/terminal/legacy/profiles:/default "'$onedark'"

################################################################################
#### Fonts
################################################################################
dconf write /org/gnome/desktop/interface/text-scaling-factor 1.25
#dconf write /org/gnome/desktop/interface/document-font-name "'Noto Sans 14'"
#dconf write /org/gnome/desktop/interface/monospace-font-name "'Monospace 14'"
#dconf write /org/gnome/desktop/interface/font-name "'Noto Sans 14'"
#dconf write /org/gnome/desktop/interface/document-font-name "'Noto Sans 14'"
#dconf write /org/gnome/desktop/interface/monospace-font-name "'Monospace 14'"
if [ -f ~/.local/share/fonts/Hack-Regular.ttf ]; then
  dconf write /$profile/use-system-font false
  dconf write /$profile/font "'Hack 12'"
  #dconf write /$profile/font "'Hack 14'"
fi
