#!/bin/bash

# shellcheck disable=SC2034
declare -f assertConfirmation &>/dev/null ||  source "$HOME/.dotfiles/install/declarations"

if assertConfirmation "Install all extra packages?"; then
    if [[ "$OS" == "elementaryOS" ]]; then
        echo "Installing extra packages to Elementary OS"
        sudo apt-get -y install audacity chromium-browser kazam geany thunderbird \
            vlc conky virtualbox griffith filezilla gksu flashplugin-installer \
            easytag curl ubuntu-restricted-extras youtube-dl git-gui hddtemp \
            lm-sensors clementine pidgin steam asunder deluge libreoffice libreoffice-gtk \
            handbrake wine zenity
    elif [[ "$OS" == "LinuxMint" ]]; then
        echo "Installing extra packages to Linux Mint"
        sudo apt-get -y install audacity chromium-browser kazam geany conky \
            virtualbox griffith filezilla gksu flashplugin-installer easytag \
            curl ubuntu-restricted-extras hddtemp lm-sensors clementine steam \
            asunder deluge handbrake wine zenity rythmbox xed
    elif [[ "$OS" == "ArchLinux" ]]; then
        echo "Installing extra packages to Arch Linux"
        sudo pacman -S --noconfirm audacity chromium virtualbox simplescreenrecorder \
            geany audacious conky filezilla easytag youtube-dl clementine asunder \
            deluge wine wine_gecko wine-mono handbrake evince baobab soundconverter \
            vorbis-tools hddtemp gnu-netcat zenity
        yaourt -Sa --noconfirm teamviewer9 pamac-aur dropbox griffith
    else
        echo "Installing extra packages to Ubuntu"
        sudo apt-get -y install audacity chromium-browser kazam geany \
            compizconfig-settings-manager unity-tweak-tool vlc conky virtualbox \
            griffith filezilla gksu flashplugin-installer easytag curl \
            ubuntu-restricted-extras youtube-dl git-gui hddtemp lm-sensors \
            clementine pidgin steam asunder deluge handbrake wine zenity
    fi
else
    clear
    read -n 1 -p "Install packages one by one? (yes/No) "
    printf '\n========================================================================'
    if [[ $REPLY =~ ^([Yy])$ ]]; then
        packages=( audacity evince kazam geany thunderbird vlc conky virtualbox filezilla \
            easytag dropbox youtube-dl git-gui steam keepassx calibre gimp audacious clementine \
            rhythmbox banshee libreoffice wine deluge )
        for app in "${packages[@]}" ; do
            clear
            read -n 1 -p "Install $app? (yes/No) "
            printf '\n========================================================================'
            if [[ $REPLY =~ ^([Yy])$ ]]; then
                sudo apt-get -y install "$app"
                echo "========================================================================"
            fi
        done
    fi
fi
