#!/bin/bash

# shellcheck disable=SC2034
declare -f assertConfirmation &>/dev/null ||  source "$HOME/.dotfiles/install/declarations"

if ! command_exists java  &&  \
    assertConfirmation "Install c compiler, gdb, jdk, jre 9, nodejs, npm?"
then
    #sudo apt-get -y remove openjdk-8*
    packages=( build-essential gcc g++ gdb make nodejs npm git dconf-cli \
        unattended-upgrades unzip shellcheck xdotool python python-setuptools \
        ruby python3 hddtemp lm-sensors curl ubuntu-restricted-extras lftp zsh \
        whois net-tools openjdk-8-jdk openjdk-8-jre )
    for app in "${packages[@]}" ; do
        sudo apt-get install -y "$app"
    done
    echo "========================================================================"
fi

#if ! command_exists junit; then
    #mkdir -p ~/tmp
    #cd ~/tmp
    # TODO: This download has to be done manually
    #wget "https://sourceforge.net/projects/junit/files/latest/download?source=files"
    #JUNIT_HOME=/usr/share/java
    # unzip junit.zip
    # mv junit* junit
    # mv junit /usr/share/java
    #export CLASSPATH=$CLASSPATH:$JUNIT_HOME/junit:.
#fi

if ! command_exists clang  &&  assertConfirmation "Install clang?"; then

    source "$INSTALL/clang-install"
    echo "========================================================================"
fi

if ! command_exists mono  &&  assertConfirmation "Install mono?"; then

    source "$INSTALL/mono-install"
fi

#if [ ! -d /usr/local/go ]  &&  assertConfirmation "Install go?"; then
#    source "$INSTALL/go-install"
#fi

if ! command_exists tsc  &&  assertConfirmation "Install TypeScript standalone server?"; then
    sudo npm install -g typescript
fi

if ! command_exists rustc  &&  assertConfirmation "Install rustc?"; then
    curl https://sh.rustup.rs -sSf | sh
    source "$HOME/.cargo/env"
fi

if ! command_exists php  &&  assertConfirmation "Install apache2, php7, mysql-server?"; then
    source "$INSTALL/lamp-install"
fi

if ! command_exists hashcat  &&  assertConfirmation "Install kali linux tools?"; then
    source "$INSTALL/katoolin"
fi

if ! (( ${autoConfirm:?} )); then
    clear
    read -n 1 -p "Install cs50 functions? (yes/No) "
    printf '\n========================================================================'
    if [[ $REPLY =~ ^([Yy]|[Ss])$ ]]; then
        source "$INSTALL/cs50"
    fi
fi
