#!/bin/bash

#exec 2>/tmp/stdout.log
#exec 2>/tmp/stderr.log
# shellcheck disable=SC2034
declare -f assertConfirmation &>/dev/null ||  source "$HOME/.dotfiles/install/declarations"

if assertConfirmation "Install c compiler, gdb, jdk, jre 9, nodejs, npm?"; then
    sudo apt-get -y remove openjdk-8*
    sudo apt-get -y install build-essential gcc g++ gdb make openjdk-9-jdk openjdk-9-jre \
        nodejs npm git dconf-cli unattended-upgrades unzip shellcheck xdotool python \
        python-setuptools ruby python3 hddtemp lm-sensors curl ubuntu-restricted-extras lftp zsh
    echo "========================================================================"
fi

if ! grep "deb-src http://apt.llvm.org/xenial/ llvm-toolchain-xenial-4.0 main"\
    /etc/apt/sources.list  &&  assertConfirmation "Install clang?"; then

    source "$DOTFILES/install/clang-4.0-install"
    echo "========================================================================"
fi

if ! grep -Fxq "deb http://download.mono-project.com/repo/debian wheezy main" \
    /etc/apt/sources.list.d/mono-xamarin.list  &&  assertConfirmation "Install mono?"; then

    source "$DOTFILES/install/mono-install"
fi

if [ ! -f /usr/local/go ]  &&  assertConfirmation "Install go?"; then
    source "$DOTFILES/install/go-install"
fi

if assertConfirmation "Install TypeScript standalone server?"; then
    npm install --save typescript
fi

if assertConfirmation "Install rustc?"; then
    curl https://sh.rustup.rs -sSf | sh
    source "$HOME/.cargo/env"
fi

if assertConfirmation "Install apache2, php7, mysql-server?"; then
    source "$DOTFILES/install/lamp-install"
fi

if assertConfirmation "Install kali linux tools?"; then
    source "$DOTFILES/install/katoolin"
fi

if (( ${autoConfirm:?} )); then
    :
else
    clear
    read -n 1 -p "Install cs50 functions? (yes/No) "
    printf '\n========================================================================'
    if [[ $REPLY =~ ^([Yy]|[Ss])$ ]]; then
        source "$DOTFILES/install/cs50"
    fi
fi
