#!/bin/bash

sudo apt-get -y autoremove tmux
sudo apt-get install -y exuberant-ctags cmake libevent-dev libncurses5-dev
wget https://github.com/tmux/tmux/releases/download/2.3/tmux-2.3.tar.gz ~/Downloads
cd ~/Downloads
tar -xzvf tmux*.tar.gz
rm tmux*.tar.gz
cd tmux-*
./configure    ||  { echo "Error executing ./config" ; exit ; }
make           ||  { echo "Error executing make" ; exit ; }
sudo make install

# Terminal con cursiva
cd ~/.dotfiles/tmux  ||  { echo "$HOME/.dotfiles/tmux doesn't exist" ; exit ; }
tic xterm-256color-italic.terminfo
mkdir -p ~/.tmux/resurrect
[ ! -f ~/.dotfiles/tmux/last ]  &&  cp ~/.dotfiles/tmux/last ~/.tmux/resurrect/
if [[ ! -d ~/.tmux/plugins/tpm ]]; then
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
fi
echo "========================================================================"
echo "Tmux installed"
echo "========================================================================"
