#!/bin/bash

clear
echo "Instalando configuración vim"
echo "========================================================================"
[ -d "$DOTFILES" ]  ||  git clone https://github.com/arturojosejr/dotfiles ~/.dotfiles
if command -v nvim 2>/dev/null; then
    curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

    nvim +PlugInstall
else
    curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

    vim -c 'PlugInstall' -c 'qa!'
    vim -u NONE -c ":Helptags" -c q
fi
echo "========================================================================"
clear
