#!/bin/bash

# shellcheck disable=SC2034
declare -f assertConfirmation &>/dev/null ||  source "$HOME/.dotfiles/install/declarations"

clear
echo "Instalando configuración vim"
echo "========================================================================"
[ -d "$DOTFILES" ]  ||  git clone https://github.com/arturojosejr/dotfiles ~/.dotfiles
if [ "$ARCH" == "64" ]; then
    cp "$DOTFILES/config/nvim/plugins/plugins64.vim" "$DOTFILES/config/nvim/plugins.vim"
else
    cp "$DOTFILES/config/nvim/plugins/plugins32.vim" "$DOTFILES/config/nvim/plugins.vim"
fi
if command -v nvim 2>/dev/null; then
    curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

    nvim +PlugInstall
else
    curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

    vim -c 'PlugInstall' -c 'qa!'
    vim -u NONE -c ":Helptags" -c q
fi
echo "========================================================================"
clear
